services:
  app:
    image: us-west1-docker.pkg.dev/hosting-server-505409/tracker-repo/soc-track:latest
    init: true
    container_name: soc_track_app
    restart: always
    volumes:
      - soc_track_db:/app/data
      - soc_track_uploads:/app/public/uploads
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/dev.db
    networks:
      - web_net

volumes:
  soc_track_db:
  soc_track_uploads:

networks:
  web_net:
    external: true
